Add Start Menu
drak00/Chess pull request #46
Opened 2021-05-28 20:03 UTC by Muazat

I added an initial menu with options; Online, offline, side and Quit. Th e offline option has four options ;Single player, Two players, Ai mode and Quit. The single player is not linked to anything yet. The two players is linked to the board. It has all other functionalities of the previous state except you cannot switch to AI mode while playing. The AI mode option displays an AI vs AI game while the quit option terminates the game.
All the above mentioned options can be selected by double clicking on them.

2021-05-29 08:09 UTC, Mrsatatima requested changes
good job.... but main_menu.py and menu.py have same contents... what is the difference.. if no difference delete one...
also after making the said changes pull from the upstream because it has been updated... this is to avoid merge conflict when merging...
make all changes and push.. welcome to steam-chess contributors

2021-05-29 15:18 UTC, Muazat commented
The main_menu and menu are two different menus. After reading the description of the add start menu, I came to realize that the Menu did not meet the description. So I had to add the main_menu that will link to the menu.

2021-05-30 19:07 UTC, drak00 commented
please fix merge conflicts so files can be merged

2021-05-30 19:21 UTC, drak00 requested changes
Nice work! Please make the corrections so we can merge!

2021-05-30 19:21 UTC, drak00 commented on menu.py
> +def player_format(message, playerSize, playerColor):
coming from java, I can understand your proclivity to using camel case, however to conform to the project's coding style which uses a more modern python convention, pls use underscores "_" to separate variable names: so playerSize would be player_size

2021-05-30 19:21 UTC, drak00 commented on menu.py
> +		name=pg.transform.scale(pg.image.load("images/menu.jfif"),(640,640)) #background image
do ensure this image is not copyrighted!

2021-05-31 09:48 UTC, Muazat commented on menu.py
> +def player_format(message, playerSize, playerColor):
Noted

2021-06-01 10:58 UTC, merged